[build]
  command = "composer install && npm run build" # O tu comando de construcción
  publish = "public" # O tu directorio de publicación

[context.production.environment]
  PHP_VERSION = "8.1"

[context.deploy-preview.environment]
  PHP_VERSION = "8.1"

[context.branch-deploy.environment]
  PHP_VERSION = "8.1"
